### ISSUE TITLE
`timetable_generator.py` fails to run

### ISSUE THREAD

**Issue by needlesslygrim** [micfong-z/OptiWay#16]
Whenever I try to run `timetable_generator.py` I get the following error:

```
Traceback (most recent call last):
  File "/home/needlesslygrim/src/rust/OptiWay/timetable_generation/timetable_generator.py", line 682, in <module>
    time_table3 = generator.generate_as_al_level()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/needlesslygrim/src/rust/OptiWay/timetable_generation/timetable_generator.py", line 561, in generate_as_al_level
    room = random.choice(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/random.py", line 373, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence
```

It originates in the [following code](https://github.com/micfong-z/OptiWay/blob/d963d06b4a8cfa70132000a6b87d0a6ed138004e/timetable_generation/timetable_generator.py#L520-L522)(formatted by me):
```python
room = random.choice(
    list(
        self.avail_rooms[floor]
        - filled_timetable[day1][p11]
        - filled_timetable[day2][p21]
        - filled_timetable[day3][p31]
        - filled_rooms[index][floor]
    )
)  # minus the as time slots as well
```

Am I missing something?

**Comment by 0010SS** [comment]
The algorithm is not robust due to the randomness of timetables and class arrangements... Please try running it multiple times.

**Comment by needlesslygrim** [comment]
Ah, that makes sense. I might open a PR that makes it loop until it isn't empty.

**Comment by needlesslygrim** [comment]
Ah, that makes sense. I might open a PR that makes the program loop until it's not empty.

**Comment by needlesslygrim** [comment]
Just written the code, once #15 is merged I'll open the PR
